apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namesace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
